name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin' # Specify the Java distribution

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run the application
      run: java -jar target/helloworld-1.0-SNAPSHOT-shaded.jar

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: target/helloworld-1.0-SNAPSHOT-shaded.jar
